release:
  github:
    owner: ekristen
    repo: example-distro-saltstack
manifest:
  version: 2
  base: example
  modes:
    - name: server
      state: example.server
      default: true
  supported_os:
    - id: ubuntu
      release: 20.04
      focal: focal

