release:
  github:
    owner: ekristen
    repo: cast-example-distro
manifest:
  version: 2
  name: example
  modes:
    - name: server
      state: example.server
      default: true
  supported_os:
    - id: ubuntu
      release: 20.04
      focal: focal

